name: Automatic Version Bump

on:
  push:
    branches:
      - main
      - 'release/*'
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      # Build step (optional). If building causes new files to appear,
      # either commit them here or ignore them. Example:
      - name: Build project
        run: pnpm run build

      # If build artifacts need to be committed:
      - name: Commit build artifacts
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          # stage all newly generated or changed files
          git add -A
          # only commit if there are changes
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "chore: commit build artifacts"
          fi

      - name: Bump version
        run: |
          # 'patch' = x.x.(x+1)
          # 'minor' = x.(x+1).0
          # 'major' = (x+1).0.0
          pnpm version patch

      - name: Push changes
        run: |
          git push --follow-tags